import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  FaFacebookSquare,
  FaYoutube,
  FaInstagram,
  FaTwitter,
  FaTiktok,
  FaLinkedin,
} from "react-icons/fa";
import congregationPic from "../public/john-price-RAZQiZOX3mU-unsplash.jpg";
import pastorPic from "../public/melyna-valle-3yiSaxd-V6Q-unsplash.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>New Life Ministries Amsterdam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="h-screen">
          <Image
            src={congregationPic}
            alt="congregation"
            className="w-full relative h-full"
          />
          <div className="absolute top-0 overflow-hidden bg-gradient-to-b md:bg-gradient-to-r from-primary/70 to-tertiary/70 h-full w-full">
            <div className="flex justify-center items-center h-full">
              <div className="text-white w-2/3 mx-auto text-center">
                <h1 className="font-bold text-6xl mb-5">
                  Welcome To New Life Ministries Amsterdam Website
                </h1>
                <p className="text-2xl mb-10 font-light">
                  Join us today as we worship the Lord
                </p>
                <Link
                  href={"#"}
                  className="px-10 py-5 bg-secondary text-gray-900 rounded-md shadow-2xl"
                >
                  Church With Us
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="py-10 bg-slate-300">
          <div className="container">
            <h2 className="font-semibold text-3xl text-center mb-10">
              About Us
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
              <Image src={pastorPic} alt="pastorPic" />
              <div>
                <p className="mb-3">
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum
                  iste numquam explicabo maxime debitis non nulla error,
                  eligendi consequuntur unde veritatis laboriosam molestias quod
                  officia voluptatem officiis distinctio eaque voluptatibus.
                </p>
                <p className="mb-10">
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum
                  iste numquam explicabo maxime debitis non nulla error,
                  eligendi consequuntur unde veritatis laboriosam molestias quod
                  officia voluptatem officiis distinctio eaque voluptatibus.
                </p>
                <Link
                  href={"#"}
                  className="px-5 py-3 bg-tertiary rounded-md text-white"
                >
                  Learn More
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div className="container">
            <h2 className="font-semibold text-3xl text-center mb-10">
              Wactch Us Online
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
              <iframe
                width="560"
                height="315"
                src="https://www.youtube.com/embed/DRCoraISqmE"
                title="YouTube video player"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowFullScreen
              ></iframe>
              <iframe
                width="560"
                height="315"
                src="https://www.youtube.com/embed/DRCoraISqmE"
                title="YouTube video player"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowFullScreen
              ></iframe>
              <iframe
                width="560"
                height="315"
                src="https://www.youtube.com/embed/DRCoraISqmE"
                title="YouTube video player"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowFullScreen
              ></iframe>
              <iframe
                width="560"
                height="315"
                src="https://www.youtube.com/embed/DRCoraISqmE"
                title="YouTube video player"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowFullScreen
              ></iframe>
            </div>
          </div>
        </section>
        <section className="py-20 font-semibold text-3xl text-center bg-gradient-to-b md:bg-gradient-to-r from-primary/90 to-tertiary/90 text-white">
          <div className="container">
            <h2 className="font-semibold mb-10 text-secondary text-3xl text-center">
              Follow Us On Social Media
            </h2>
          </div>
          <div className="flex items-center justify-center">
            <a
              href="#"
              target="_blank"
              rel="noopener noreferrer"
              className="px-2 hover:text-secondary"
            >
              <FaFacebookSquare />
            </a>
            <a
              href="#"
              target="_blank"
              rel="noopener noreferrer"
              className="px-2 hover:text-secondary"
            >
              <FaYoutube />
            </a>
            <a
              href="#"
              target="_blank"
              rel="noopener noreferrer"
              className="px-2 hover:text-secondary"
            >
              <FaInstagram />
            </a>
            <a
              href="#"
              target="_blank"
              rel="noopener noreferrer"
              className="px-2 hover:text-secondary"
            >
              <FaTwitter />
            </a>
            <a
              href="#"
              target="_blank"
              rel="noopener noreferrer"
              className="px-2 hover:text-secondary"
            >
              <FaTiktok />
            </a>
            <a
              href="#"
              target="_blank"
              rel="noopener noreferrer"
              className="px-2 hover:text-secondary"
            >
              <FaLinkedin />
            </a>
          </div>
        </section>
        <section className="py-10 bg-slate-300">
          <div className="container">
            <h2 className="font-semibold text-3xl text-center mb-10">
              Our Weekly Services
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-10">
              <div className="">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Exercitationem ipsam adipisci rem quisquam excepturi odit earum
                quis architecto inventore nemo ducimus velit harum, perferendis
                quaerat reprehenderit explicabo aspernatur officia aperiam.
              </div>
              <div className="">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Exercitationem ipsam adipisci rem quisquam excepturi odit earum
                quis architecto inventore nemo ducimus velit harum, perferendis
                quaerat reprehenderit explicabo aspernatur officia aperiam.
              </div>
              <div className="">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Exercitationem ipsam adipisci rem quisquam excepturi odit earum
                quis architecto inventore nemo ducimus velit harum, perferendis
                quaerat reprehenderit explicabo aspernatur officia aperiam.
              </div>
              <div className="">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Exercitationem ipsam adipisci rem quisquam excepturi odit earum
                quis architecto inventore nemo ducimus velit harum, perferendis
                quaerat reprehenderit explicabo aspernatur officia aperiam.
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
